### ISSUE TITLE
Fix/Escape quotes

### ISSUE THREAD

**Issue by AbraaoAlves** [AbraaoAlves/gulp-html-to-ts#3]
Html: 

``` html
    <a href=''><i></i></a>
```

TS:
module app {export var html = '<a href=\'\'><i></i></a>';}

**Comment by rlasjunies** [comment]
Hi @AbraaoAlves,

 I am still interested to have the fix and the enhancement in the repo. 
 I have not a lot of experience in sharing code, how should I proceed.

Thank in advance for your support

Richard

**Comment by AbraaoAlves** [comment]
Thanks for your interest and dedication.

I have not had a lot of confidence to accept pull request without automated tests, although there were none. I know our gulpfile is something, but is still far from being automated.

I think our next step is to transform the gulpfile in a real test suite, preferably with mochajs. Here the issue #4.

Thanks for your preference.

**Comment by AbraaoAlves** [comment]
closed at #2

**Comment by rlasjunies** [comment]
perfect, do you have experience in mochajs? mine is closed to null.
